"""
Generate 100 Premium Retail Products across 10 Departments
Outputs TypeScript mock catalog and seeds Firestore.
"""

import json

# 100 Curated Products across 10 Departments
PRODUCTS = [
    # --- 1. Furniture & Workspaces (prod-001 to prod-010) ---
    {
        "id": "prod-001",
        "name": "Nordic Oak Minimalist Ergonomic Desk Chair",
        "category": "Furniture",
        "price": 249.00,
        "originalPrice": 299.00,
        "rating": 4.85,
        "reviewsCount": 342,
        "stock": 24,
        "image": "https://images.unsplash.com/photo-1592078615290-033ee584e267?auto=format&fit=crop&w=800&q=80",
        "description": "Clean Scandinavian silhouette constructed with steam-bent solid white oak and breathable memory foam cushioning.",
        "features": ["Solid White Oak frame", "Pneumatic 4-inch height lift", "Tilt lock mechanism with Lumbar Flex", "Weight capacity: 330 lbs"],
        "tags": ["scandinavian", "minimalist", "ergonomic", "oak", "workspace", "home office"],
        "elasticity": -1.35,
        "inStoreAisle": "Aisle 4B (Home Office)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-002",
        "name": "Solid Walnut Motorized Height-Adjustable Standing Desk",
        "category": "Furniture",
        "price": 649.00,
        "originalPrice": 749.00,
        "rating": 4.92,
        "reviewsCount": 218,
        "stock": 16,
        "image": "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=800&q=80",
        "description": "Premium 60x30 inch solid American walnut surface with dual ultra-quiet brushless motors and 4 memory presets.",
        "features": ["Dual synchronized motors", "Anti-collision safety sensor", "Integrated cable management raceway", "300 lb lift capacity"],
        "tags": ["standing desk", "walnut", "motorized", "ergonomic", "executive", "office"],
        "elasticity": -1.15,
        "inStoreAisle": "Aisle 4A (Desks & Workstations)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-003",
        "name": "Mid-Century Modern Velvet Accent Lounge Armchair",
        "category": "Furniture",
        "price": 329.00,
        "originalPrice": 389.00,
        "rating": 4.78,
        "reviewsCount": 164,
        "stock": 12,
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80",
        "description": "Deep emerald green plush velvet upholstery with tapered matte brass legs and high-resilience foam core.",
        "features": ["Stain-resistant velvet", "Brushed gold steel hairpin legs", "High-density pocket spring cushion", "Easy 10-minute assembly"],
        "tags": ["velvet", "armchair", "living room", "mid-century", "emerald", "lounge"],
        "elasticity": -1.55,
        "inStoreAisle": "Aisle 5C (Seating & Lounges)",
        "returnRiskScore": 12
    },
    {
        "id": "prod-004",
        "name": "Modular Birch Plywood 5-Tier Bookshelf System",
        "category": "Furniture",
        "price": 189.50,
        "originalPrice": 220.00,
        "rating": 4.71,
        "reviewsCount": 89,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80",
        "description": "Architectural open-back modular shelving system crafted from FSC-certified Baltic birch with concealed brackets.",
        "features": ["FSC-certified Baltic birch", "Tool-free interlocking assembly", "Holds up to 75 lbs per shelf", "Wall-anchor hardware included"],
        "tags": ["bookshelf", "storage", "birch", "modular", "minimalist", "shelving"],
        "elasticity": -1.40,
        "inStoreAisle": "Aisle 5B (Storage & Shelving)",
        "returnRiskScore": 7
    },
    {
        "id": "prod-005",
        "name": "Aerospace Aluminum Dual Heavy-Duty Monitor Arm",
        "category": "Furniture",
        "price": 119.00,
        "originalPrice": 149.00,
        "rating": 4.88,
        "reviewsCount": 420,
        "stock": 55,
        "image": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80",
        "description": "Gas-spring articulated dual monitor mount supporting up to 34-inch displays with 360-degree rotation.",
        "features": ["Holds 4.4 to 19.8 lbs per arm", "VESA 75x75 & 100x100 compatible", "Integrated dual USB 3.0 passthrough", "C-clamp and grommet mount"],
        "tags": ["monitor arm", "desk accessory", "ergonomic", "dual screen", "workspace"],
        "elasticity": -1.80,
        "inStoreAisle": "Aisle 4C (Desk Hardware)",
        "returnRiskScore": 9
    },
    {
        "id": "prod-006",
        "name": "Full-Grain Italian Leather Executive Desk Blotter Pad",
        "category": "Furniture",
        "price": 79.00,
        "originalPrice": 95.00,
        "rating": 4.82,
        "reviewsCount": 210,
        "stock": 42,
        "image": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80",
        "description": "Vegetable-tanned full-grain leather mat with non-slip suede backing and water-resistant wax burnishing.",
        "features": ["36 x 18 inch generous coverage", "Smooth optical mouse tracking", "Hand-stitched perimeter border", "Ages with natural patina"],
        "tags": ["leather", "desk pad", "desk mat", "executive", "handcrafted"],
        "elasticity": -1.25,
        "inStoreAisle": "Aisle 4D (Desk Accessories)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-007",
        "name": "Adjustable Ergonomic Under-Desk Footrest with Massage Rollers",
        "category": "Furniture",
        "price": 49.99,
        "originalPrice": 65.00,
        "rating": 4.65,
        "reviewsCount": 178,
        "stock": 60,
        "image": "https://images.unsplash.com/photo-1580481077195-c3a821a58875?auto=format&fit=crop&w=800&q=80",
        "description": "Multi-angle tilting footrest designed to relieve lower back pressure and improve circulation during long workdays.",
        "features": ["3 height settings (4, 5.5, 6.7 in)", "30-degree tilt lock", "Textured acupressure surface", "Non-skid rubberized feet"],
        "tags": ["footrest", "ergonomic", "posture", "home office", "comfort"],
        "elasticity": -1.70,
        "inStoreAisle": "Aisle 4C (Ergonomics)",
        "returnRiskScore": 8
    },
    {
        "id": "prod-008",
        "name": "Minimalist Japanese Hinoki Cypress Entryway Storage Bench",
        "category": "Furniture",
        "price": 275.00,
        "originalPrice": 320.00,
        "rating": 4.90,
        "reviewsCount": 94,
        "stock": 14,
        "image": "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=800&q=80",
        "description": "Naturally aromatic Japanese Hinoki wood bench with slatted shoe shelf and traditional mortise-and-tenon joinery.",
        "features": ["Solid Hinoki cypress wood", "Traditional joinery with no visible screws", "Holds up to 400 lbs", "Lower shelf stores 6 pairs of shoes"],
        "tags": ["entryway", "bench", "japanese", "hinoki", "cypress", "minimalist"],
        "elasticity": -1.10,
        "inStoreAisle": "Aisle 5A (Entryway & Hall)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-009",
        "name": "Matte Black Architectural LED Counterbalance Task Lamp",
        "category": "Furniture",
        "price": 89.00,
        "originalPrice": 110.00,
        "rating": 4.80,
        "reviewsCount": 265,
        "stock": 38,
        "image": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80",
        "description": "Precision spring-balanced arm with 3000K-6000K stepless color temperature adjustment and 95+ CRI illumination.",
        "features": ["High CRI 95+ flicker-free LED", "Touch dimmer with memory", "Clamp or heavy weighted base", "50,000 hour rated lifespan"],
        "tags": ["lamp", "task light", "lighting", "led", "architectural", "matte black"],
        "elasticity": -1.60,
        "inStoreAisle": "Aisle 4E (Lighting & Lamps)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-010",
        "name": "Sound-Absorbing Felt Hexagonal Acoustic Wall Panels (12-Pack)",
        "category": "Furniture",
        "price": 54.00,
        "originalPrice": 69.00,
        "rating": 4.75,
        "reviewsCount": 312,
        "stock": 70,
        "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
        "description": "High-density recycled polyester fiber tiles dampening studio echoes and keyboard noise in video calls.",
        "features": ["0.92 NRC sound absorption rating", "100% recycled PET fiber", "Beveled edge geometric design", "Self-adhesive peel-and-stick backing"],
        "tags": ["acoustic", "soundproofing", "wall panels", "studio", "home office"],
        "elasticity": -1.90,
        "inStoreAisle": "Aisle 4D (Office Acoustics)",
        "returnRiskScore": 7
    },

    # --- 2. Electronics & Studio Audio (prod-011 to prod-020) ---
    {
        "id": "prod-011",
        "name": "Aura Pro Active Noise-Canceling Wireless Studio Headphones",
        "category": "Electronics",
        "price": 349.99,
        "originalPrice": 399.99,
        "rating": 4.92,
        "reviewsCount": 1120,
        "stock": 48,
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
        "description": "Flagship 40mm beryllium drivers paired with hybrid adaptive ANC, lossless spatial audio, and 45-hour continuous battery life.",
        "features": ["Lossless LDAC & aptX Adaptive", "Hybrid 6-mic ANC array with Transparency", "45h battery life with fast charge", "Magnetic memory foam earcups"],
        "tags": ["audio", "anc", "wireless", "headphones", "bluetooth", "studio"],
        "elasticity": -1.82,
        "inStoreAisle": "Aisle 1A (Personal Audio)",
        "returnRiskScore": 14
    },
    {
        "id": "prod-012",
        "name": "VocalStream XLR & USB-C Cardioid Condenser Studio Microphone",
        "category": "Electronics",
        "price": 149.00,
        "originalPrice": 179.00,
        "rating": 4.86,
        "reviewsCount": 540,
        "stock": 36,
        "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80",
        "description": "Dual-output 24-bit/96kHz broadcast microphone with built-in DSP limiter, headphone monitor, and shock mount.",
        "features": ["Dual USB-C and XLR outputs", "24-bit/96kHz high-resolution ADC", "Zero-latency 3.5mm monitor jack", "Heavy metal desktop base"],
        "tags": ["microphone", "podcast", "streaming", "studio", "condenser", "usb-c"],
        "elasticity": -1.65,
        "inStoreAisle": "Aisle 1B (Creator & Studio)",
        "returnRiskScore": 8
    },
    {
        "id": "prod-013",
        "name": "Nova 4K Ultra HD 60FPS Webcam with Dual Stereo AI Microphones",
        "category": "Electronics",
        "price": 129.50,
        "originalPrice": 159.00,
        "rating": 4.74,
        "reviewsCount": 380,
        "stock": 42,
        "image": "https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=800&q=80",
        "description": "Sony STARVIS CMOS sensor delivering crisp 4K imagery even in low light, with motorized privacy shutter.",
        "features": ["Sony STARVIS 4K sensor", "Auto-framing AI tracking", "Physical sliding privacy shutter", "Tripod thread and monitor mount"],
        "tags": ["webcam", "4k", "video calls", "streaming", "remote work"],
        "elasticity": -1.75,
        "inStoreAisle": "Aisle 1C (Peripherals)",
        "returnRiskScore": 10
    },
    {
        "id": "prod-014",
        "name": "Keystroke 75% Wireless Mechanical Keyboard (Hot-Swappable)",
        "category": "Electronics",
        "price": 119.00,
        "originalPrice": 139.00,
        "rating": 4.91,
        "reviewsCount": 860,
        "stock": 50,
        "image": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
        "description": "CNC aluminum chassis with gasket mount, factory-lubed linear switches, and dye-sub PBT keycaps.",
        "features": ["Gasket-mounted acoustic dampening", "Hot-swappable 5-pin PCB", "Tri-mode: 2.4G / Bluetooth 5.2 / USB-C", "4000mAh rechargeable battery"],
        "tags": ["keyboard", "mechanical", "hot-swap", "wireless", "gasket mount"],
        "elasticity": -1.45,
        "inStoreAisle": "Aisle 1C (Keyboards & Mice)",
        "returnRiskScore": 9
    },
    {
        "id": "prod-015",
        "name": "EchoPulse True Wireless Noise-Canceling Earbuds (IPX7)",
        "category": "Electronics",
        "price": 129.00,
        "originalPrice": 159.00,
        "rating": 4.81,
        "reviewsCount": 670,
        "stock": 65,
        "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80",
        "description": "Graphene dynamic drivers with 40dB active noise cancellation, wireless charging case, and IPX7 sweat resistance.",
        "features": ["IPX7 waterproof rating", "32 hours total playback with case", "Qi wireless charging enabled", "Custom EQ via companion app"],
        "tags": ["earbuds", "wireless", "anc", "waterproof", "running", "audio"],
        "elasticity": -1.95,
        "inStoreAisle": "Aisle 1A (Personal Audio)",
        "returnRiskScore": 15
    },
    {
        "id": "prod-016",
        "name": "MagCharge 10,000mAh Ultra-Slim Magnetic Wireless Power Bank",
        "category": "Electronics",
        "price": 49.00,
        "originalPrice": 59.00,
        "rating": 4.79,
        "reviewsCount": 490,
        "stock": 80,
        "image": "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80",
        "description": "Strong magnetic snap-on 15W Qi2 wireless charger with 20W PD USB-C bidirectional fast charging port.",
        "features": ["15W Qi2 certified wireless charging", "20W USB-C Power Delivery", "Foldable kickstand included", "Airline travel approved (38.5Wh)"],
        "tags": ["power bank", "charger", "magsafe", "magnetic", "portable battery"],
        "elasticity": -1.85,
        "inStoreAisle": "Aisle 1D (Charging & Cables)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-017",
        "name": "Audiophile Hi-Res Portable DAC & Balanced Headphone Amplifier",
        "category": "Electronics",
        "price": 199.00,
        "originalPrice": 229.00,
        "rating": 4.88,
        "reviewsCount": 142,
        "stock": 25,
        "image": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80",
        "description": "Dual ESS Sabre ES9219C DAC chips decoding PCM 32-bit/384kHz and DSD256 with 4.4mm balanced output.",
        "features": ["Dual ESS Sabre DAC architecture", "4.4mm balanced + 3.5mm single-ended", "MQA full decoder hardware", "OLED status display screen"],
        "tags": ["dac", "audiophile", "amp", "hi-res", "headphone amp"],
        "elasticity": -1.20,
        "inStoreAisle": "Aisle 1A (Audiophile Gear)",
        "returnRiskScore": 11
    },
    {
        "id": "prod-018",
        "name": "ScreenGlow Smart Monitor Light Bar with Wireless Dial Controller",
        "category": "Electronics",
        "price": 69.00,
        "originalPrice": 85.00,
        "rating": 4.83,
        "reviewsCount": 510,
        "stock": 58,
        "image": "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=800&q=80",
        "description": "Asymmetrical optical design eliminating screen glare with 2.4GHz wireless rotary dial for brightness and color temp.",
        "features": ["Zero screen reflection optics", "2700K - 6500K stepless CCT", "Wireless rotary control dial", "Auto light sensor dimmer"],
        "tags": ["light bar", "monitor light", "desk lamp", "ergonomic", "workspace"],
        "elasticity": -1.70,
        "inStoreAisle": "Aisle 1C (Peripherals)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-019",
        "name": "Reference 5-Inch Active Studio Monitor Speakers (Pair)",
        "category": "Electronics",
        "price": 289.00,
        "originalPrice": 339.00,
        "rating": 4.90,
        "reviewsCount": 230,
        "stock": 18,
        "image": "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80",
        "description": "Bi-amplified Class D studio monitors with woven composite woofers and silk dome tweeters for flat acoustic response.",
        "features": ["100W combined Class D power", "Acoustic space tuning switches", "Balanced TRS and RCA inputs", "Custom front bass reflex ports"],
        "tags": ["speakers", "studio monitors", "audio", "music production", "reference"],
        "elasticity": -1.30,
        "inStoreAisle": "Aisle 1B (Studio Audio)",
        "returnRiskScore": 13
    },
    {
        "id": "prod-020",
        "name": "Apex GPS Multisport Fitness Smartwatch (Titanium Sapphire)",
        "category": "Electronics",
        "price": 449.00,
        "originalPrice": 499.00,
        "rating": 4.87,
        "reviewsCount": 395,
        "stock": 28,
        "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80",
        "description": "Grade 5 titanium bezel with scratch-resistant sapphire crystal, dual-frequency GNSS, and 24-day battery life.",
        "features": ["Dual-frequency multi-satellite GPS", "Optical heart rate and SpO2 sensor", "Offline topographic mapping", "100m water resistance rating"],
        "tags": ["smartwatch", "gps", "fitness", "titanium", "running", "wearable"],
        "elasticity": -1.10,
        "inStoreAisle": "Aisle 1D (Wearables & Health)",
        "returnRiskScore": 16
    },

    # --- 3. Apparel & Technical Outerwear (prod-021 to prod-030) ---
    {
        "id": "prod-021",
        "name": "Alpine Traverse 3-Layer GORE-TEX Waterproof Shell Jacket",
        "category": "Apparel",
        "price": 389.00,
        "originalPrice": 420.00,
        "rating": 4.79,
        "reviewsCount": 189,
        "stock": 19,
        "image": "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80",
        "description": "Rugged weather armor engineered with 28,000mm hydrostatic head waterproofing, fully taped micro-seams, and underarm pit zips.",
        "features": ["3-layer GORE-TEX Pro membrane", "StormHood compatible with ski helmets", "WaterTight pit zips for ventilation", "RECCO rescue reflector integrated"],
        "tags": ["outerwear", "gore-tex", "waterproof", "hiking", "skiing", "winter"],
        "elasticity": -0.92,
        "inStoreAisle": "Aisle 8C (Technical Outerwear)",
        "returnRiskScore": 8
    },
    {
        "id": "prod-022",
        "name": "100% Merino Wool 250g Thermal Base Layer Crewneck",
        "category": "Apparel",
        "price": 98.00,
        "originalPrice": 115.00,
        "rating": 4.88,
        "reviewsCount": 420,
        "stock": 52,
        "image": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
        "description": "Superfine 18.5-micron New Zealand merino wool naturally regulating body temperature and resisting odor for multi-day treks.",
        "features": ["100% pure merino wool (250gsm)", "Flatlock non-chafing seams", "Natural antimicrobial odor resistance", "Raglan sleeve athletic cut"],
        "tags": ["merino wool", "base layer", "thermal", "hiking", "winter", "outdoor apparel"],
        "elasticity": -1.25,
        "inStoreAisle": "Aisle 8B (Thermal Layers)",
        "returnRiskScore": 7
    },
    {
        "id": "prod-023",
        "name": "Recycled Cordura All-Weather Commuter Roll-Top Backpack (28L)",
        "category": "Apparel",
        "price": 149.00,
        "originalPrice": 175.00,
        "rating": 4.84,
        "reviewsCount": 340,
        "stock": 38,
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
        "description": "Ballistic 840D Cordura pack with waterproof roll-top closure, suspended 16-inch laptop compartment, and luggage pass-through.",
        "features": ["840D Recycled Cordura fabric", "Weatherproof seam-sealed roll-top", "Magnetic Fidlock sternum strap", "Dedicated side-access laptop sleeve"],
        "tags": ["backpack", "commuter", "cordura", "waterproof", "travel", "laptop bag"],
        "elasticity": -1.40,
        "inStoreAisle": "Aisle 6C (Travel & Bags)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-024",
        "name": "All-Day Stretch Performance Chino Pants (Water-Repellent DWR)",
        "category": "Apparel",
        "price": 88.00,
        "originalPrice": 105.00,
        "rating": 4.76,
        "reviewsCount": 510,
        "stock": 64,
        "image": "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80",
        "description": "Technical 4-way stretch fabric blending organic cotton and recycled nylon with hidden zippered security passport pockets.",
        "features": ["4-way mechanical stretch fabric", "DWR water & stain resistant finish", "Concealed YKK zippered pocket", "Gusseted crotch mobility"],
        "tags": ["pants", "chinos", "travel apparel", "stretch", "commuter"],
        "elasticity": -1.60,
        "inStoreAisle": "Aisle 7A (Men's & Women's Pants)",
        "returnRiskScore": 14
    },
    {
        "id": "prod-025",
        "name": "Ultralight 850-Fill Power Goose Down Insulated Vest",
        "category": "Apparel",
        "price": 179.00,
        "originalPrice": 210.00,
        "rating": 4.86,
        "reviewsCount": 215,
        "stock": 30,
        "image": "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80",
        "description": "RDS-certified 850-fill water-resistant down encased in 10D ripstop nylon shell weighing a mere 7.2 ounces.",
        "features": ["850-fill RDS certified goose down", "10D Pertex Quantum ripstop nylon", "Packs into its own chest pocket", "Micro-fleece lined hand pockets"],
        "tags": ["vest", "down", "insulated", "lightweight", "winter", "layering"],
        "elasticity": -1.15,
        "inStoreAisle": "Aisle 8C (Insulation & Down)",
        "returnRiskScore": 9
    },
    {
        "id": "prod-026",
        "name": "Seamless Bamboo Active Breathable Training T-Shirt",
        "category": "Apparel",
        "price": 38.00,
        "originalPrice": 45.00,
        "rating": 4.73,
        "reviewsCount": 630,
        "stock": 90,
        "image": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
        "description": "Knitted seamless construction utilizing bamboo viscose fibers for moisture wicking and chafe-free marathon runs.",
        "features": ["70% Bamboo viscose, 30% Elastane", "Seamless circular knit technology", "Engineered mesh ventilation zones", "UPF 50+ sun protection"],
        "tags": ["t-shirt", "running", "training", "bamboo", "activewear"],
        "elasticity": -1.80,
        "inStoreAisle": "Aisle 7C (Activewear)",
        "returnRiskScore": 8
    },
    {
        "id": "prod-027",
        "name": "Heavyweight 400gsm French Terry Cotton Hoodie",
        "category": "Apparel",
        "price": 110.00,
        "originalPrice": 130.00,
        "rating": 4.90,
        "reviewsCount": 440,
        "stock": 45,
        "image": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80",
        "description": "Pre-shrunk custom-milled 400gsm combed organic cotton with double-layered hood and ribbed side panels.",
        "features": ["400gsm 100% organic cotton", "Ribbed action gusset side panels", "Nickel eyelets & braided drawstrings", "Reinforced kangaroo pocket"],
        "tags": ["hoodie", "cotton", "streetwear", "heavyweight", "fleece"],
        "elasticity": -1.30,
        "inStoreAisle": "Aisle 7B (Sweatshirts & Hoodies)",
        "returnRiskScore": 10
    },
    {
        "id": "prod-028",
        "name": "Japanese Selvage 13.5oz Raw Denim Jeans",
        "category": "Apparel",
        "price": 165.00,
        "originalPrice": 195.00,
        "rating": 4.82,
        "reviewsCount": 185,
        "stock": 26,
        "image": "https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=800&q=80",
        "description": "Woven on vintage Toyoda shuttle looms in Okayama, Japan with custom copper hardware and chain-stitched hems.",
        "features": ["13.5oz Okayama red-line selvage denim", "100% long-staple cotton", "Custom solid copper button fly", "Natural indigo dyed yarns"],
        "tags": ["denim", "selvage", "raw denim", "jeans", "japanese denim"],
        "elasticity": -1.05,
        "inStoreAisle": "Aisle 7D (Denim & Jeans)",
        "returnRiskScore": 16
    },
    {
        "id": "prod-029",
        "name": "Weather-Resistant Waxed Canvas Chore Field Coat",
        "category": "Apparel",
        "price": 220.00,
        "originalPrice": 260.00,
        "rating": 4.85,
        "reviewsCount": 130,
        "stock": 20,
        "image": "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80",
        "description": "British Millerain 10oz waxed canvas with corduroy collar, blanket flannel interior lining, and brass snaps.",
        "features": ["British Millerain waxed cotton", "Corduroy-lined collar & cuffs", "Wool flannel interior insulation", "Dual bellow cargo pockets"],
        "tags": ["chore coat", "waxed canvas", "jacket", "workwear", "heritage"],
        "elasticity": -1.20,
        "inStoreAisle": "Aisle 8A (Heritage Outerwear)",
        "returnRiskScore": 11
    },
    {
        "id": "prod-030",
        "name": "TrailGrip Vibram Megagrip Waterproof Hiking Shoes",
        "category": "Apparel",
        "price": 160.00,
        "originalPrice": 185.00,
        "rating": 4.87,
        "reviewsCount": 360,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80",
        "description": "Trail runners featuring Vibram Megagrip lugged outsoles, eVent waterproof booties, and rock protection plates.",
        "features": ["Vibram Megagrip sticky rubber lugs", "eVent waterproof breathable lining", "EVA dual-density midsole", "Reinforced TPU toe bumper"],
        "tags": ["shoes", "hiking", "trail running", "waterproof", "vibram"],
        "elasticity": -1.45,
        "inStoreAisle": "Aisle 8E (Footwear)",
        "returnRiskScore": 18
    },

    # --- 4. Kitchen & Dining (prod-031 to prod-040) ---
    {
        "id": "prod-031",
        "name": "Artisan Precision Pour-Over Gooseneck Kettle (Variable Temp)",
        "category": "Kitchen",
        "price": 139.50,
        "originalPrice": 159.00,
        "rating": 4.88,
        "reviewsCount": 542,
        "stock": 32,
        "image": "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80",
        "description": "Counterbalanced pour spout with PID digital temperature controller offering 1-degree precision for specialty pour-over brewing.",
        "features": ["1200W rapid boil element", "PID digital temperature control (104-212°F)", "60-minute temperature hold function", "Counterbalanced ergonomic handle"],
        "tags": ["coffee", "pour over", "kettle", "gooseneck", "barista", "kitchen"],
        "elasticity": -1.45,
        "inStoreAisle": "Aisle 6A (Brew Gear)",
        "returnRiskScore": 7
    },
    {
        "id": "prod-032",
        "name": "Enamelled Cast Iron 5.5-Quart Round Dutch Oven",
        "category": "Kitchen",
        "price": 175.00,
        "originalPrice": 210.00,
        "rating": 4.93,
        "reviewsCount": 680,
        "stock": 22,
        "image": "https://images.unsplash.com/photo-1584990347449-3665a38be93c?auto=format&fit=crop&w=800&q=80",
        "description": "Heavy-duty cast iron pot coated in vibrant chip-resistant gloss enamel, engineered for superior heat distribution and slow braises.",
        "features": ["Even heat retention up to 500°F", "Chip-resistant porcelain enamel finish", "Tight-fitting lid with self-basting spikes", "Oven, stovetop, and induction ready"],
        "tags": ["dutch oven", "cast iron", "cookware", "baking", "braising"],
        "elasticity": -1.15,
        "inStoreAisle": "Aisle 6B (Cookware)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-033",
        "name": "Japanese 67-Layer VG-10 Damascus 8-Inch Chef's Knife",
        "category": "Kitchen",
        "price": 125.00,
        "originalPrice": 150.00,
        "rating": 4.91,
        "reviewsCount": 410,
        "stock": 28,
        "image": "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=800&q=80",
        "description": "Forged VG-10 high-carbon Japanese steel core hardened to 60±2 HRC, encased in 66 layers of folded Damascus steel.",
        "features": ["67-layer Damascus pattern", "VG-10 steel core (60±2 HRC)", "Octagonal Pakkawood handle", "Razor-sharp 15-degree edge bevel"],
        "tags": ["knife", "chef knife", "damascus", "culinary", "cutlery"],
        "elasticity": -1.30,
        "inStoreAisle": "Aisle 6C (Cutlery)",
        "returnRiskScore": 9
    },
    {
        "id": "prod-034",
        "name": "Smart Conical Burr Coffee Grinder (40 Grind Settings)",
        "category": "Kitchen",
        "price": 169.00,
        "originalPrice": 199.00,
        "rating": 4.83,
        "reviewsCount": 390,
        "stock": 25,
        "image": "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80",
        "description": "Commercial-grade 40mm stainless steel conical burrs with digital timer and anti-static ionizer to reduce grind mess.",
        "features": ["40 precision stepped grind settings", "Anti-static grind chute technology", "Digital dose timer to 0.1s precision", "High-torque low-RPM motor"],
        "tags": ["coffee grinder", "espresso", "burr grinder", "coffee", "barista"],
        "elasticity": -1.50,
        "inStoreAisle": "Aisle 6A (Coffee Gear)",
        "returnRiskScore": 12
    },
    {
        "id": "prod-035",
        "name": "Precision Immersion Sous-Vide Cooker with WiFi App Control",
        "category": "Kitchen",
        "price": 119.00,
        "originalPrice": 139.00,
        "rating": 4.80,
        "reviewsCount": 310,
        "stock": 34,
        "image": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
        "description": "1100-watt immersion circulator holding water bath temperatures to within 0.1°F for restaurant-quality steak doneness.",
        "features": ["1100W heating capacity", "Accurate to ±0.1°F / 0.05°C", "WiFi and Bluetooth remote monitoring", "Adjustable clamp fits any stockpot"],
        "tags": ["sous vide", "culinary", "smart kitchen", "steak", "cooking"],
        "elasticity": -1.60,
        "inStoreAisle": "Aisle 6D (Small Appliances)",
        "returnRiskScore": 11
    },
    {
        "id": "prod-036",
        "name": "Mineral B Non-Stick 11-Inch Blue Carbon Steel Frying Pan",
        "category": "Kitchen",
        "price": 69.50,
        "originalPrice": 85.00,
        "rating": 4.87,
        "reviewsCount": 480,
        "stock": 40,
        "image": "https://images.unsplash.com/photo-1584990347449-3665a38be93c?auto=format&fit=crop&w=800&q=80",
        "description": "Natural beeswax protective finish, developing a slick non-stick patina naturally over time without harmful PTFE/PFOA chemicals.",
        "features": ["100% natural carbon steel", "Free of PTFE, PFOA, and forever chemicals", "Safe for induction and high-heat searing", "French curved handle design"],
        "tags": ["skillet", "carbon steel", "pan", "cookware", "non-toxic"],
        "elasticity": -1.35,
        "inStoreAisle": "Aisle 6B (Cookware)",
        "returnRiskScore": 8
    },
    {
        "id": "prod-037",
        "name": "End-Grain Hard Rock Maple Butcher Block Cutting Board",
        "category": "Kitchen",
        "price": 95.00,
        "originalPrice": 120.00,
        "rating": 4.92,
        "reviewsCount": 260,
        "stock": 20,
        "image": "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=800&q=80",
        "description": "Self-healing end-grain North American hard maple board preserving knife sharpness with deep perimeter juice groove.",
        "features": ["1.75 inch thick solid end-grain maple", "Recessed hand grips for easy carrying", "Deep perimeter juice reservoir groove", "Treated with food-grade mineral oil"],
        "tags": ["cutting board", "butcher block", "maple", "culinary", "prep"],
        "elasticity": -1.20,
        "inStoreAisle": "Aisle 6C (Cutlery & Boards)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-038",
        "name": "Barista Digital Gram Scale with 0.1g Auto-Timer Function",
        "category": "Kitchen",
        "price": 38.00,
        "originalPrice": 48.00,
        "rating": 4.79,
        "reviewsCount": 590,
        "stock": 65,
        "image": "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80",
        "description": "Fast-response sensor accurate to 0.1 grams with flow-rate indicator and silicone heat-insulating drip tray.",
        "features": ["0.1g precision resolution", "Integrated automatic brew flow timer", "Rechargeable USB-C lithium battery", "Waterproof silicone protective pad"],
        "tags": ["scale", "coffee scale", "kitchen scale", "baking", "barista"],
        "elasticity": -1.75,
        "inStoreAisle": "Aisle 6A (Coffee Gear)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-039",
        "name": "Handmade Speckled Ceramic Ramen & Noodle Bowls (Set of 4)",
        "category": "Kitchen",
        "price": 58.00,
        "originalPrice": 72.00,
        "rating": 4.86,
        "reviewsCount": 220,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80",
        "description": "Stoneware bowls fired at 1280°C with organic reactive matte glaze, microwave and dishwasher safe.",
        "features": ["36 oz generous capacity", "Includes 4 matching wooden spoons", "Lead-free food-safe reactive glaze", "Microwave and dishwasher safe"],
        "tags": ["bowls", "ceramic", "ramen", "dinnerware", "stoneware"],
        "elasticity": -1.40,
        "inStoreAisle": "Aisle 6E (Dinnerware)",
        "returnRiskScore": 9
    },
    {
        "id": "prod-040",
        "name": "Double-Walled Borosilicate Insulated Glass Coffee Mugs (Set of 4)",
        "category": "Kitchen",
        "price": 34.00,
        "originalPrice": 42.00,
        "rating": 4.81,
        "reviewsCount": 430,
        "stock": 50,
        "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
        "description": "Thermal insulated glasses keeping latte drinks hot without burning hands or sweating condensation.",
        "features": ["12 oz capacity per glass", "Hand-blown thermal borosilicate glass", "Condensation-free double wall barrier", "Microwave and freezer safe"],
        "tags": ["mugs", "glassware", "coffee", "latte", "drinkware"],
        "elasticity": -1.65,
        "inStoreAisle": "Aisle 6E (Glassware)",
        "returnRiskScore": 13
    },

    # --- 5. Fitness & Athletics (prod-041 to prod-050) ---
    {
        "id": "prod-041",
        "name": "Ultra-Dense Eco Natural Tree Rubber Alignment Yoga Mat (6mm)",
        "category": "Fitness",
        "price": 68.00,
        "originalPrice": 85.00,
        "rating": 4.89,
        "reviewsCount": 420,
        "stock": 55,
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80",
        "description": "Non-slip polyurethane top layer over natural sustainably harvested tree rubber base with laser-etched alignment guides.",
        "features": ["6mm joint-cushioning density", "Laser-etched body alignment lines", "Zero-slip sweaty grip surface", "Includes cotton carrying sling"],
        "tags": ["yoga", "yoga mat", "rubber", "pilates", "fitness", "eco-friendly"],
        "elasticity": -1.45,
        "inStoreAisle": "Aisle 9B (Yoga & Pilates)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-042",
        "name": "Quick-Select Adjustable Dumbbell Set (5 to 52.5 lbs Pair)",
        "category": "Fitness",
        "price": 349.00,
        "originalPrice": 399.00,
        "rating": 4.93,
        "reviewsCount": 780,
        "stock": 14,
        "image": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80",
        "description": "Space-saving dumbbell system replacing 15 sets of weights with a turn of the dial from 5 to 52.5 pounds.",
        "features": ["Adjusts in 2.5 lb increments", "Replaces 15 pairs of free weights", "Molded steel plates with durable casing", "Includes two storage cradles"],
        "tags": ["dumbbells", "strength", "weights", "home gym", "adjustable"],
        "elasticity": -1.10,
        "inStoreAisle": "Aisle 9A (Strength & Free Weights)",
        "returnRiskScore": 10
    },
    {
        "id": "prod-043",
        "name": "Deep-Tissue Percussion Massage Therapy Gun (Brushless 16mm)",
        "category": "Fitness",
        "price": 149.00,
        "originalPrice": 189.00,
        "rating": 4.87,
        "reviewsCount": 610,
        "stock": 38,
        "image": "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80",
        "description": "Quiet brushless motor delivering 16mm deep stall-force percussive therapy with 6 specialized interchangeable heads.",
        "features": ["16mm amplitude deep tissue reach", "Ultra-quiet motor (<45dB)", "6 interchangeable therapeutic heads", "6-hour lithium battery life"],
        "tags": ["massage gun", "recovery", "percussion", "muscle", "therapy"],
        "elasticity": -1.60,
        "inStoreAisle": "Aisle 9D (Recovery & Mobility)",
        "returnRiskScore": 12
    },
    {
        "id": "prod-044",
        "name": "Heavy-Duty Fabric Resistance Glute & Booty Bands (Set of 3)",
        "category": "Fitness",
        "price": 24.50,
        "originalPrice": 32.00,
        "rating": 4.82,
        "reviewsCount": 940,
        "stock": 120,
        "image": "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?auto=format&fit=crop&w=800&q=80",
        "description": "Non-slip cotton latex blend bands that will never roll up, pinch skin, or snap during squats and hip thrusts.",
        "features": ["3 resistance levels (Light/Med/Heavy)", "Non-slip inner rubber grip strips", "Thick durable fabric weave", "Mesh carrying pouch included"],
        "tags": ["resistance bands", "glutes", "legs", "warmup", "fitness"],
        "elasticity": -1.95,
        "inStoreAisle": "Aisle 9C (Bands & Accessories)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-045",
        "name": "High-Density Speckled EPP Grid Foam Roller (36-Inch)",
        "category": "Fitness",
        "price": 32.00,
        "originalPrice": 40.00,
        "rating": 4.79,
        "reviewsCount": 380,
        "stock": 45,
        "image": "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80",
        "description": "Firm expanded polypropylene roller supporting full spinal alignment and myofascial trigger-point release.",
        "features": ["Full 36-inch length for spine support", "Eco-friendly recyclable EPP material", "Maintains shape under 500 lbs", "Textured non-slip grip surface"],
        "tags": ["foam roller", "mobility", "stretching", "recovery", "back pain"],
        "elasticity": -1.70,
        "inStoreAisle": "Aisle 9D (Recovery & Mobility)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-046",
        "name": "Aluminum High-Speed Bearing Jump Rope with Dual Steel Cables",
        "category": "Fitness",
        "price": 22.00,
        "originalPrice": 28.00,
        "rating": 4.84,
        "reviewsCount": 510,
        "stock": 80,
        "image": "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?auto=format&fit=crop&w=800&q=80",
        "description": "360-degree dual ball bearing swivel handles enabling friction-free double-unders and high-intensity cardio conditioning.",
        "features": ["Dual 360-degree ball bearings", "Knurled non-slip aluminum handles", "Includes two coated steel cables", "Thumb-screw length adjuster"],
        "tags": ["jump rope", "cardio", "boxing", "crossfit", "conditioning"],
        "elasticity": -1.85,
        "inStoreAisle": "Aisle 9C (Cardio Accessories)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-047",
        "name": "Cast Iron Powder-Coated Kettlebell (35 lbs / 16 kg)",
        "category": "Fitness",
        "price": 62.00,
        "originalPrice": 75.00,
        "rating": 4.90,
        "reviewsCount": 270,
        "stock": 25,
        "image": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80",
        "description": "Single-cast solid gravity-molded iron kettlebell with textured matte powder coat for superior chalk retention.",
        "features": ["Machined flat bottom for stable base", "Color-coded ring for quick weight identification", "Wide handle for two-handed swings", "Seam-free gravity cast construction"],
        "tags": ["kettlebell", "strength", "crossfit", "swings", "functional fitness"],
        "elasticity": -1.25,
        "inStoreAisle": "Aisle 9A (Free Weights)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-048",
        "name": "Insulated Stainless Steel 32oz Protein Shaker Bottle",
        "category": "Fitness",
        "price": 28.00,
        "originalPrice": 35.00,
        "rating": 4.81,
        "reviewsCount": 670,
        "stock": 75,
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80",
        "description": "Double-wall vacuum insulation keeping drinks icy cold for 24 hours with silent whisk agitator.",
        "features": ["Double-wall vacuum insulated 18/8 steel", "Twist-lock leak-proof lid", "Silent built-in blending grate", "Odor and stain resistant interior"],
        "tags": ["shaker bottle", "water bottle", "protein", "supplements", "gym"],
        "elasticity": -1.75,
        "inStoreAisle": "Aisle 9C (Hydration & Shakers)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-049",
        "name": "Textured Rubber Slam Ball for Core Conditioning (20 lbs)",
        "category": "Fitness",
        "price": 45.00,
        "originalPrice": 55.00,
        "rating": 4.77,
        "reviewsCount": 190,
        "stock": 30,
        "image": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80",
        "description": "Thick tread-grooved rubber shell filled with iron sand, designed to absorb high-impact drops with zero bounce.",
        "features": ["Zero bounce dead-weight design", "Tire-tread grip texture", "Heavy-duty burst-proof PVC shell", "Great for explosive core work"],
        "tags": ["slam ball", "medicine ball", "core", "hiit", "conditioning"],
        "elasticity": -1.50,
        "inStoreAisle": "Aisle 9A (Functional Gear)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-050",
        "name": "Solid Portuguese Cork Yoga Blocks & Strap Set",
        "category": "Fitness",
        "price": 32.00,
        "originalPrice": 40.00,
        "rating": 4.86,
        "reviewsCount": 310,
        "stock": 50,
        "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80",
        "description": "Two firm natural cork blocks paired with an 8-foot organic cotton D-ring strap for deepening stretches.",
        "features": ["100% sustainable cork from Portugal", "Beveled comfortable edges", "Includes 8ft cotton alignment strap", "Naturally antimicrobial and firm"],
        "tags": ["yoga blocks", "cork", "props", "flexibility", "stretching"],
        "elasticity": -1.65,
        "inStoreAisle": "Aisle 9B (Yoga & Props)",
        "returnRiskScore": 4
    },

    # --- 6. Home & Living / Decor (prod-051 to prod-060) ---
    {
        "id": "prod-051",
        "name": "Fluted Stoneware Minimalist Plant Pot & Drainage Saucer",
        "category": "Home & Decor",
        "price": 38.00,
        "originalPrice": 48.00,
        "rating": 4.88,
        "reviewsCount": 340,
        "stock": 60,
        "image": "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80",
        "description": "Matte white ribbed ceramic pot with concealed bottom drainage hole and matching catch saucer.",
        "features": ["8-inch diameter planter", "Built-in drainage hole with plug", "Matching saucer preserves surfaces", "High-fired chip-resistant stoneware"],
        "tags": ["planter", "pot", "indoor plants", "ceramic", "minimalist", "decor"],
        "elasticity": -1.60,
        "inStoreAisle": "Aisle 5A (Indoor Garden & Pots)",
        "returnRiskScore": 7
    },
    {
        "id": "prod-052",
        "name": "Ultrasonic Ceramic Stone Essential Oil Diffuser (500ml)",
        "category": "Home & Decor",
        "price": 65.00,
        "originalPrice": 80.00,
        "rating": 4.84,
        "reviewsCount": 520,
        "stock": 42,
        "image": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80",
        "description": "Handcrafted matte porcelain ceramic cover with whisper-quiet ultrasonic atomization and warm ambient glow.",
        "features": ["500ml large capacity tank (16h mist)", "Warm ambient LED nightlight", "Automatic waterless safety shut-off", "BPA-free medical grade reservoir"],
        "tags": ["diffuser", "aromatherapy", "essential oils", "ceramic", "wellness"],
        "elasticity": -1.75,
        "inStoreAisle": "Aisle 5D (Home Fragrance)",
        "returnRiskScore": 9
    },
    {
        "id": "prod-053",
        "name": "100% French Washed Linen Queen Duvet Cover & Pillow Sham Set",
        "category": "Home & Decor",
        "price": 189.00,
        "originalPrice": 225.00,
        "rating": 4.92,
        "reviewsCount": 290,
        "stock": 25,
        "image": "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80",
        "description": "Woven from certified Normandy flax linen, pre-washed for effortless drape, breathable in summer and insulating in winter.",
        "features": ["100% French flax linen", "Corner interior duvet tie anchors", "Mother-of-pearl button closure", "Gets softer with every laundry wash"],
        "tags": ["bedding", "linen", "duvet", "french flax", "bedroom"],
        "elasticity": -1.15,
        "inStoreAisle": "Aisle 5E (Bedding & Linens)",
        "returnRiskScore": 12
    },
    {
        "id": "prod-054",
        "name": "Hand-Poured Soy Wax Scented Candle in Amber Glass (Teakwood & Tobacco)",
        "category": "Home & Decor",
        "price": 26.00,
        "originalPrice": 32.00,
        "rating": 4.90,
        "reviewsCount": 780,
        "stock": 95,
        "image": "https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80",
        "description": "Clean-burning USA soy wax with lead-free cotton wick offering 50 hours of complex cedar, patchouli, and leather notes.",
        "features": ["50-hour clean burn time", "100% USA grown soy wax", "Phthalate-free fine fragrance oils", "Reusable apothecary amber jar"],
        "tags": ["candle", "soy candle", "home fragrance", "amber glass", "cozy"],
        "elasticity": -1.90,
        "inStoreAisle": "Aisle 5D (Candles & Scents)",
        "returnRiskScore": 3
    },
    {
        "id": "prod-055",
        "name": "Hand-Tufted Moroccan Geometric 100% New Zealand Wool Area Rug (5x8)",
        "category": "Home & Decor",
        "price": 320.00,
        "originalPrice": 380.00,
        "rating": 4.86,
        "reviewsCount": 140,
        "stock": 15,
        "image": "https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&w=800&q=80",
        "description": "Plush 1-inch pile hand-tufted from un-dyed virgin wool with subtle charcoal tribal diamond motifs.",
        "features": ["100% pure New Zealand wool", "Thick 1-inch soft pile height", "Cotton canvas backing", "Naturally stain resistant"],
        "tags": ["rug", "wool rug", "moroccan", "living room", "carpet"],
        "elasticity": -1.10,
        "inStoreAisle": "Aisle 5B (Rugs & Flooring)",
        "returnRiskScore": 14
    },
    {
        "id": "prod-056",
        "name": "Solid Brushed Brass 12-Inch Silent Quartz Wall Clock",
        "category": "Home & Decor",
        "price": 59.00,
        "originalPrice": 75.00,
        "rating": 4.81,
        "reviewsCount": 260,
        "stock": 38,
        "image": "https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=800&q=80",
        "description": "Spun brass rim with matte ivory dial and sweep silent movement with no annoying ticking sound.",
        "features": ["Silent sweep quartz mechanism", "Spun genuine brushed brass frame", "Flat mineral glass lens", "Operates on 1 AA battery"],
        "tags": ["clock", "wall clock", "brass", "minimalist", "decor"],
        "elasticity": -1.55,
        "inStoreAisle": "Aisle 5C (Wall Decor)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-057",
        "name": "Woven Cotton Rope Laundry & Toy Storage Basket (Set of 2)",
        "category": "Home & Decor",
        "price": 42.00,
        "originalPrice": 52.00,
        "rating": 4.83,
        "reviewsCount": 610,
        "stock": 70,
        "image": "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80",
        "description": "Natural unbleached cotton coil basket with reinforced stitched handles, collapsible for easy storage.",
        "features": ["100% natural organic cotton rope", "Extra large 18 x 16 inch volume", "Reinforced slit carry handles", "Chemical and odor free"],
        "tags": ["basket", "storage", "laundry", "cotton", "nursery"],
        "elasticity": -1.80,
        "inStoreAisle": "Aisle 5B (Organization)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-058",
        "name": "Organic Waffle Knit Turkish Cotton Bath Towel 4-Piece Bundle",
        "category": "Home & Decor",
        "price": 84.00,
        "originalPrice": 105.00,
        "rating": 4.89,
        "reviewsCount": 350,
        "stock": 40,
        "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80",
        "description": "Honeycomb waffle weave woven from long-staple Aegean Turkish cotton that dries in half the time of terry towels.",
        "features": ["100% Aegean Turkish cotton", "Fast-drying honeycomb weave", "Includes 2 bath towels & 2 hand towels", "OEKO-TEX Standard 100 certified"],
        "tags": ["towels", "bath", "turkish cotton", "waffle weave", "bathroom"],
        "elasticity": -1.40,
        "inStoreAisle": "Aisle 5E (Bath & Towels)",
        "returnRiskScore": 7
    },
    {
        "id": "prod-059",
        "name": "Brushed Nickel Frameless Arched Vanity Wall Mirror (24x36)",
        "category": "Home & Decor",
        "price": 139.00,
        "originalPrice": 170.00,
        "rating": 4.85,
        "reviewsCount": 190,
        "stock": 20,
        "image": "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80",
        "description": "High-definition 4mm silver float glass with aluminum alloy arched frame and shatter-proof backing.",
        "features": ["4mm copper-free HD silver glass", "Rust-proof aluminum frame", "Shatter-proof explosion membrane", "Reinforced D-ring wall hangers"],
        "tags": ["mirror", "arched mirror", "bathroom", "entryway", "vanity"],
        "elasticity": -1.30,
        "inStoreAisle": "Aisle 5C (Mirrors)",
        "returnRiskScore": 15
    },
    {
        "id": "prod-060",
        "name": "Handmade Chunky Chenille Knit Throw Blanket (50x60)",
        "category": "Home & Decor",
        "price": 68.00,
        "originalPrice": 85.00,
        "rating": 4.87,
        "reviewsCount": 440,
        "stock": 48,
        "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80",
        "description": "Non-shedding ultra-soft jumbo chenille yarn hand-knitted for cozy couch draping and warmth.",
        "features": ["Ultra-soft breathable chenille", "Zero-shedding synthetic fibers", "Machine washable on gentle cycle", "Weighted comfortable drape"],
        "tags": ["blanket", "throw", "knit", "chenille", "cozy", "living room"],
        "elasticity": -1.65,
        "inStoreAisle": "Aisle 5E (Throws & Blankets)",
        "returnRiskScore": 8
    },

    # --- 7. Beauty & Wellness (prod-061 to prod-070) ---
    {
        "id": "prod-061",
        "name": "Pure Sugarcane 100% Squalane Facial Hydration Oil (100ml)",
        "category": "Beauty",
        "price": 34.00,
        "originalPrice": 42.00,
        "rating": 4.91,
        "reviewsCount": 820,
        "stock": 85,
        "image": "https://images.unsplash.com/photo-1608248597359-bb4f4340e4e6?auto=format&fit=crop&w=800&q=80",
        "description": "Weightless bio-fermented sugarcane squalane penetrating deep into moisture barriers without clogging pores.",
        "features": ["100% plant-derived squalane", "Non-comedogenic & fragrance-free", "Safe for face, body, and split ends", "Dermatologist tested & vegan"],
        "tags": ["skincare", "squalane", "facial oil", "hydration", "beauty", "clean beauty"],
        "elasticity": -1.70,
        "inStoreAisle": "Aisle 2B (Serums & Oils)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-062",
        "name": "Sonic Silicone Micro-Exfoliating Facial Cleansing Brush",
        "category": "Beauty",
        "price": 69.00,
        "originalPrice": 89.00,
        "rating": 4.84,
        "reviewsCount": 430,
        "stock": 50,
        "image": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80",
        "description": "T-sonic pulses with ultra-hygienic silicone bristles dislodging 99.5% of dirt, oil, and makeup residue.",
        "features": ["IPX8 fully waterproof body", "8000 sonic pulsations per minute", "Medical-grade antibacterial silicone", "USB magnetic charge lasts 6 months"],
        "tags": ["cleansing brush", "sonic", "facial tool", "beauty device", "skincare"],
        "elasticity": -1.55,
        "inStoreAisle": "Aisle 2A (Beauty Devices)",
        "returnRiskScore": 9
    },
    {
        "id": "prod-063",
        "name": "Multi-Peptide Matrixyl 3000 Youth Restorative Night Serum",
        "category": "Beauty",
        "price": 48.00,
        "originalPrice": 58.00,
        "rating": 4.89,
        "reviewsCount": 650,
        "stock": 70,
        "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80",
        "description": "Triple-action peptide blend supporting collagen synthesis, fine line smoothing, and cellular elasticity overnight.",
        "features": ["Matrixyl 3000 & Copper Peptides", "Multi-molecular hyaluronic acid", "Cruelty-free & paraben-free", "Fast-absorbing silky texture"],
        "tags": ["serum", "peptides", "anti-aging", "skincare", "night serum"],
        "elasticity": -1.45,
        "inStoreAisle": "Aisle 2B (Serums & Treatments)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-064",
        "name": "Natural Rose Quartz Gua Sha & Dual-End Facial Roller Kit",
        "category": "Beauty",
        "price": 28.00,
        "originalPrice": 36.00,
        "rating": 4.82,
        "reviewsCount": 730,
        "stock": 90,
        "image": "https://images.unsplash.com/photo-1512290900672-1f486518a22d?auto=format&fit=crop&w=800&q=80",
        "description": "Authentic Brazilian rose quartz stones hand-carved to boost lymphatic drainage and relieve jaw tension.",
        "features": ["100% natural Brazilian rose quartz", "Reinforced squeak-free metal frame", "Promotes lymphatic face drainage", "Includes velvet storage travel pouch"],
        "tags": ["gua sha", "facial roller", "rose quartz", "lymphatic", "beauty tool"],
        "elasticity": -1.80,
        "inStoreAisle": "Aisle 2A (Facial Tools)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-065",
        "name": "Sheer Zinc Oxide Mineral Face Sunscreen SPF 50+ (Matte Finish)",
        "category": "Beauty",
        "price": 32.00,
        "originalPrice": 38.00,
        "rating": 4.86,
        "reviewsCount": 590,
        "stock": 80,
        "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
        "description": "Non-nano 20% zinc oxide providing broad spectrum UVA/UVB protection with zero white cast and primer finish.",
        "features": ["20% Non-nano zinc oxide formula", "Reef-safe and water-resistant (80m)", "Leaves zero chalky white residue", "Niacinamide for sebum regulation"],
        "tags": ["sunscreen", "spf 50", "mineral sunscreen", "zinc oxide", "skincare"],
        "elasticity": -1.65,
        "inStoreAisle": "Aisle 2C (Sun & Suncare)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-066",
        "name": "Pure Mulberry Silk 22-Momme Contoured Blackout Sleep Mask",
        "category": "Beauty",
        "price": 36.00,
        "originalPrice": 45.00,
        "rating": 4.93,
        "reviewsCount": 910,
        "stock": 65,
        "image": "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80",
        "description": "High-grade 6A mulberry silk reducing eye friction, preventing sleep creases, with zero eyelid pressure.",
        "features": ["100% Grade 6A 22-momme silk", "3D eye socket relief contouring", "Adjustable snag-free elastic band", "100% complete blackout seal"],
        "tags": ["sleep mask", "silk", "mulberry silk", "wellness", "sleep"],
        "elasticity": -1.85,
        "inStoreAisle": "Aisle 2D (Sleep & Wellness)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-067",
        "name": "Rosemary & Biotin Follicle Stimulating Scalp Treatment Serum",
        "category": "Beauty",
        "price": 26.00,
        "originalPrice": 32.00,
        "rating": 4.80,
        "reviewsCount": 840,
        "stock": 75,
        "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=800&q=80",
        "description": "Cold-pressed rosemary oil, biotin, and peppermint refreshing scalp roots and encouraging denser hair growth.",
        "features": ["Pure rosemary essential oil & biotin", "Lightweight daily leave-in dropper", "Soothes dry, flaky scalp itchiness", "Sulfate-free and color-safe"],
        "tags": ["haircare", "scalp serum", "rosemary oil", "biotin", "hair growth"],
        "elasticity": -1.75,
        "inStoreAisle": "Aisle 2E (Hair Care)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-068",
        "name": "Ceramide Barrier Defense Intensive Overnight Lip Butter Mask",
        "category": "Beauty",
        "price": 18.00,
        "originalPrice": 22.00,
        "rating": 4.90,
        "reviewsCount": 1150,
        "stock": 110,
        "image": "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=800&q=80",
        "description": "Shea butter and multi-ceramides dissolving dry flakes overnight for cushiony, plumped lips.",
        "features": ["Contains 5 essential ceramides", "Organic shea and murmuru butter", "Subtle natural vanilla scent", "Includes applicator spatula"],
        "tags": ["lip mask", "lip butter", "ceramides", "skincare", "lip care"],
        "elasticity": -1.95,
        "inStoreAisle": "Aisle 2C (Lip & Eye Care)",
        "returnRiskScore": 3
    },
    {
        "id": "prod-069",
        "name": "Dead Sea Mineral & Lavender Calming Epsom Bath Soak (32oz)",
        "category": "Beauty",
        "price": 22.00,
        "originalPrice": 28.00,
        "rating": 4.85,
        "reviewsCount": 490,
        "stock": 60,
        "image": "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=800&q=80",
        "description": "Pure magnesium sulfate salts blended with French lavender and sweet almond oil for muscle recovery.",
        "features": ["Pure pharmaceutical grade Epsom salt", "Infused with genuine French lavender", "Magnesium soothes sore muscles", "Resealable pouch preserves scent"],
        "tags": ["bath soak", "epsom salt", "bath salts", "lavender", "recovery"],
        "elasticity": -1.60,
        "inStoreAisle": "Aisle 2D (Bath & Body)",
        "returnRiskScore": 3
    },
    {
        "id": "prod-070",
        "name": "Sandalwood & Jojoba Beard Conditioning Oil & Boar Bristle Brush",
        "category": "Beauty",
        "price": 32.00,
        "originalPrice": 40.00,
        "rating": 4.83,
        "reviewsCount": 380,
        "stock": 45,
        "image": "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80",
        "description": "Non-greasy organic argan and jojoba beard oil with pearwood boar bristle brush for grooming.",
        "features": ["100% natural cold-pressed carrier oils", "Warm sandalwood and cedar scent", "Solid pearwood boar bristle brush", "Eliminates beard itch and dandruff"],
        "tags": ["beard oil", "grooming", "men's grooming", "shaving", "beard brush"],
        "elasticity": -1.50,
        "inStoreAisle": "Aisle 2E (Men's Grooming)",
        "returnRiskScore": 4
    },

    # --- 8. Groceries & Gourmet Pantry (prod-071 to prod-080) ---
    {
        "id": "prod-071",
        "name": "Ethiopian Yirgacheffe Single-Origin Whole Bean Coffee (2lb)",
        "category": "Gourmet",
        "price": 28.50,
        "originalPrice": 34.00,
        "rating": 4.94,
        "reviewsCount": 890,
        "stock": 65,
        "image": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
        "description": "Light roast washed heirloom coffee bursting with jasmine aromatics, bergamot citrus, and honey sweetness.",
        "features": ["Single-origin Yirgacheffe, Ethiopia", "Specialty Grade 1 washed beans", "Fresh nitrogen-flushed roast valve bag", "Tasting notes: Jasmine, Peach, Honey"],
        "tags": ["coffee", "whole bean", "specialty coffee", "ethiopian", "yirgacheffe", "gourmet"],
        "elasticity": -1.75,
        "inStoreAisle": "Aisle 3A (Specialty Coffee & Tea)",
        "returnRiskScore": 3
    },
    {
        "id": "prod-072",
        "name": "Cold-Pressed Extra Virgin Olive Oil from Crete, Greece (750ml)",
        "category": "Gourmet",
        "price": 24.00,
        "originalPrice": 30.00,
        "rating": 4.91,
        "reviewsCount": 620,
        "stock": 80,
        "image": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80",
        "description": "Single-estate Koroneiki olives cold-pressed within 4 hours of harvest, <0.3% acidity with peppery polyphenol finish.",
        "features": ["100% Greek Koroneiki olives", "Acidity < 0.28% (Ultra-low)", "Dark UV-blocking glass bottle", "High polyphenol antioxidant count"],
        "tags": ["olive oil", "evoo", "extra virgin", "greek", "culinary", "pantry"],
        "elasticity": -1.50,
        "inStoreAisle": "Aisle 3C (Oils & Vinegars)",
        "returnRiskScore": 2
    },
    {
        "id": "prod-073",
        "name": "Raw Wildflower Honeycomb & Honey Jar from Pacific Northwest (16oz)",
        "category": "Gourmet",
        "price": 19.50,
        "originalPrice": 24.00,
        "rating": 4.88,
        "reviewsCount": 440,
        "stock": 70,
        "image": "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80",
        "description": "Unpasteurized raw honeycomb packed in wildflower honey, preserving natural pollen and enzymes.",
        "features": ["100% raw unheated and unfiltered", "Contains whole edible honeycomb square", "Sustainably harvested in Oregon", "Natural source of bee propolis"],
        "tags": ["honey", "raw honey", "honeycomb", "artisan", "sweetener"],
        "elasticity": -1.60,
        "inStoreAisle": "Aisle 3B (Honey & Spreads)",
        "returnRiskScore": 2
    },
    {
        "id": "prod-074",
        "name": "Ceremonial Grade Uji Matcha Green Tea Powder from Kyoto (30g)",
        "category": "Gourmet",
        "price": 32.00,
        "originalPrice": 39.00,
        "rating": 4.92,
        "reviewsCount": 510,
        "stock": 55,
        "image": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
        "description": "First-harvest shade-grown tencha stone-ground in Uji, Kyoto with vibrant emerald green color and umami creaminess.",
        "features": ["First harvest spring ceremonial grade", "Shade-grown for 25 days", "Zero bitterness silky mouthfeel", "Sealed tin with freshness pull-ring"],
        "tags": ["matcha", "green tea", "japanese tea", "ceremonial matcha", "uji"],
        "elasticity": -1.40,
        "inStoreAisle": "Aisle 3A (Tea & Matcha)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-075",
        "name": "Artisanal Single-Origin 72% Dark Chocolate Bars (Variety 4-Pack)",
        "category": "Gourmet",
        "price": 22.00,
        "originalPrice": 26.00,
        "rating": 4.89,
        "reviewsCount": 680,
        "stock": 90,
        "image": "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80",
        "description": "Bean-to-bar dark chocolate sourced from Madagascar, Ecuador, Colombia, and Ghana, sweetened with organic cane sugar.",
        "features": ["Direct trade cacao beans", "Only 2 ingredients: Cacao & Organic Sugar", "Soy-free, dairy-free & vegan", "Pack of 4 distinct origin profiles"],
        "tags": ["chocolate", "dark chocolate", "bean to bar", "artisan", "sweets"],
        "elasticity": -1.85,
        "inStoreAisle": "Aisle 3D (Chocolates & Confectionery)",
        "returnRiskScore": 2
    },
    {
        "id": "prod-076",
        "name": "Traditional Aged Balsamic Vinegar of Modena IGP (12-Year Barrel, 250ml)",
        "category": "Gourmet",
        "price": 36.00,
        "originalPrice": 45.00,
        "rating": 4.95,
        "reviewsCount": 380,
        "stock": 40,
        "image": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80",
        "description": "Aged in sequential oak, chestnut, and cherry casks in Modena, Italy with syrupy density and sweet acidity.",
        "features": ["Certified IGP Modena, Italy", "Aged in wood casks for 12 years", "Dense syrupy pour (1.34 density)", "Delicious over Parmigiano or strawberries"],
        "tags": ["balsamic vinegar", "modena", "italian", "vinegar", "gourmet"],
        "elasticity": -1.20,
        "inStoreAisle": "Aisle 3C (Oils & Vinegars)",
        "returnRiskScore": 3
    },
    {
        "id": "prod-077",
        "name": "Organic Gluten-Free Thick Rolled Oats (5 lb Bulk Bag)",
        "category": "Gourmet",
        "price": 16.50,
        "originalPrice": 20.00,
        "rating": 4.82,
        "reviewsCount": 730,
        "stock": 100,
        "image": "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
        "description": "Non-GMO certified gluten-free kiln-toasted whole rolled oat groats with satisfying chewy texture.",
        "features": ["Certified gluten-free and USDA Organic", "High in soluble beta-glucan fiber", "Thick-cut rolled texture", "Heavy-duty resealable zipper pouch"],
        "tags": ["oats", "breakfast", "gluten free", "organic", "oatmeal"],
        "elasticity": -1.90,
        "inStoreAisle": "Aisle 3E (Grains & Cereals)",
        "returnRiskScore": 1
    },
    {
        "id": "prod-078",
        "name": "Himalayan Pink Rock Salt Ceramic Mill Grinder (14oz Refillable)",
        "category": "Gourmet",
        "price": 14.00,
        "originalPrice": 18.00,
        "rating": 4.84,
        "reviewsCount": 590,
        "stock": 85,
        "image": "https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=800&q=80",
        "description": "Pure unrefined pink crystal salt mined from ancient seabeds in Khewra, packaged with adjustable ceramic grinder.",
        "features": ["100% natural unrefined crystal salt", "84 trace mineral elements", "Adjustable ceramic burr grinder", "Refillable glass body container"],
        "tags": ["salt", "pink salt", "himalayan salt", "spices", "grinder"],
        "elasticity": -1.95,
        "inStoreAisle": "Aisle 3C (Spices & Salts)",
        "returnRiskScore": 2
    },
    {
        "id": "prod-079",
        "name": "Roasted & Lightly Salted California Pistachios (2 lb Resealable Bag)",
        "category": "Gourmet",
        "price": 24.50,
        "originalPrice": 29.00,
        "rating": 4.90,
        "reviewsCount": 810,
        "stock": 75,
        "image": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80",
        "description": "Colossal San Joaquin valley pistachios dry roasted with sea salt for wholesome plant protein and healthy fats.",
        "features": ["Colossal grade California pistachios", "Dry roasted with sea salt (no oil added)", "6g plant protein per serving", "Resealable stay-fresh foil bag"],
        "tags": ["pistachios", "nuts", "healthy snacks", "snacks", "protein"],
        "elasticity": -1.80,
        "inStoreAisle": "Aisle 3D (Nuts & Dried Fruit)",
        "returnRiskScore": 2
    },
    {
        "id": "prod-080",
        "name": "Organic Cold-Brew Herbal Chamomile & Lavender Loose Leaf Tea (8oz)",
        "category": "Gourmet",
        "price": 18.00,
        "originalPrice": 22.00,
        "rating": 4.87,
        "reviewsCount": 420,
        "stock": 60,
        "image": "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
        "description": "Whole Egyptian chamomile flowers blended with French lavender and spearmint for caffeine-free evening relaxation.",
        "features": ["Caffeine-free 100% organic herbs", "Whole intact dried flower buds", "Delicious hot or steeped as cold brew", "Aroma-sealed airtight metal tin"],
        "tags": ["tea", "chamomile", "herbal tea", "loose leaf", "calm"],
        "elasticity": -1.70,
        "inStoreAisle": "Aisle 3A (Tea)",
        "returnRiskScore": 3
    },

    # --- 9. Outdoor & Travel Gear (prod-081 to prod-090) ---
    {
        "id": "prod-081",
        "name": "Ultralight 2-Person 3-Season Freestanding Backpacking Tent (3.2 lbs)",
        "category": "Outdoor",
        "price": 299.00,
        "originalPrice": 349.00,
        "rating": 4.91,
        "reviewsCount": 310,
        "stock": 18,
        "image": "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=80",
        "description": "DAC Featherlite aluminum poles with silicone-treated 15D ripstop nylon rainfly and dual vestibules.",
        "features": ["Ultralight trail weight: 3 lbs 3 oz", "DAC Featherlite NSL pole system", "Dual doors and dry-entry vestibules", "1200mm waterproof polyurethane floor"],
        "tags": ["tent", "camping", "backpacking", "ultralight", "shelter", "hiking"],
        "elasticity": -1.15,
        "inStoreAisle": "Aisle 8D (Tents & Camping)",
        "returnRiskScore": 11
    },
    {
        "id": "prod-082",
        "name": "Portable Manual Camping Espresso Machine with Pressure Gauge",
        "category": "Outdoor",
        "price": 89.00,
        "originalPrice": 110.00,
        "rating": 4.83,
        "reviewsCount": 420,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80",
        "description": "Hand-powered piston producing 18 bars of hydraulic pressure for rich crema espresso on mountain summits.",
        "features": ["18-bar manual extraction pump", "Works with ground coffee or capsules", "Integrated thermal insulated cup", "Weighs only 336 grams"],
        "tags": ["espresso", "camping coffee", "outdoor", "portable", "coffee maker"],
        "elasticity": -1.65,
        "inStoreAisle": "Aisle 8B (Camp Kitchen)",
        "returnRiskScore": 9
    },
    {
        "id": "prod-083",
        "name": "Titanium Ultralight 3-Piece Camp Cookset & Spork Bundle (180g)",
        "category": "Outdoor",
        "price": 54.00,
        "originalPrice": 65.00,
        "rating": 4.89,
        "reviewsCount": 510,
        "stock": 48,
        "image": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80",
        "description": "Pure Grade 1 titanium pot with folding handles, frying lid, and polished bowl spork nesting inside.",
        "features": ["Grade 1 biocompatible titanium", "Pot nests a 110g isobutane canister", "Graduated fluid volume stamps", "Mesh drawstring storage sack"],
        "tags": ["cookware", "titanium", "backpacking", "camp kitchen", "spork"],
        "elasticity": -1.45,
        "inStoreAisle": "Aisle 8B (Camp Cookware)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-084",
        "name": "Solar Portable Power Station 300W / 288Wh LiFePO4 Battery",
        "category": "Outdoor",
        "price": 239.00,
        "originalPrice": 289.00,
        "rating": 4.88,
        "reviewsCount": 230,
        "stock": 16,
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
        "description": "Long-life LiFePO4 cells offering 3,000+ cycles, 300W pure sine wave AC inverter, and 100W USB-C PD.",
        "features": ["3000+ cycle LiFePO4 battery chemistry", "Pure sine wave 300W AC outlet", "100W bi-directional USB-C PD port", "MPPT solar charge controller built-in"],
        "tags": ["power station", "solar generator", "battery", "camping", "emergency"],
        "elasticity": -1.20,
        "inStoreAisle": "Aisle 8E (Camp Electronics)",
        "returnRiskScore": 14
    },
    {
        "id": "prod-085",
        "name": "Compact Aircraft Aluminum Folding Camp Chair (Weighs 2 lbs)",
        "category": "Outdoor",
        "price": 79.00,
        "originalPrice": 95.00,
        "rating": 4.85,
        "reviewsCount": 380,
        "stock": 40,
        "image": "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=80",
        "description": "Shock-corded aluminum frame with 600D ripstop polyester mesh, supporting up to 300 pounds.",
        "features": ["Packs down to 14 x 4 inches", "7075 aircraft-grade aluminum alloy", "Holds up to 300 lbs safely", "Breathable side mesh ventilation"],
        "tags": ["camp chair", "folding chair", "backpacking", "outdoor", "lightweight"],
        "elasticity": -1.55,
        "inStoreAisle": "Aisle 8A (Camp Furniture)",
        "returnRiskScore": 7
    },
    {
        "id": "prod-086",
        "name": "Submersible Waterproof 500D PVC Dry Bag Duffel (40L)",
        "category": "Outdoor",
        "price": 46.00,
        "originalPrice": 58.00,
        "rating": 4.80,
        "reviewsCount": 490,
        "stock": 55,
        "image": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
        "description": "IPX6 roll-top waterproof bag protecting clothes and electronics while kayaking, boating, or hiking in storms.",
        "features": ["500D heavy-duty tarpaulin PVC", "Roll-down watertight seal buckle", "Detachable padded backpack straps", "Front splash-proof zippered pocket"],
        "tags": ["dry bag", "waterproof", "kayaking", "boating", "travel duffel"],
        "elasticity": -1.75,
        "inStoreAisle": "Aisle 8D (Water Sports)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-087",
        "name": "USB-C Rechargeable 1000-Lumen Dual-Beam LED Headlamp",
        "category": "Outdoor",
        "price": 38.00,
        "originalPrice": 48.00,
        "rating": 4.87,
        "reviewsCount": 710,
        "stock": 70,
        "image": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80",
        "description": "Bright flood and spotlight LED with red night-vision mode, IPX8 waterproof rating, and 60-degree tilt.",
        "features": ["1000 lumen max output", "Red LED night vision preserves eyes", "IPX8 waterproof to 2 meters", "USB-C fast charge with battery level LED"],
        "tags": ["headlamp", "flashlight", "running", "camping", "hiking", "illumination"],
        "elasticity": -1.85,
        "inStoreAisle": "Aisle 8E (Lighting & Knives)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-088",
        "name": "Titanium Polarized UV400 Sunglasses with Hydrophobic Coating",
        "category": "Outdoor",
        "price": 95.00,
        "originalPrice": 120.00,
        "rating": 4.82,
        "reviewsCount": 320,
        "stock": 42,
        "image": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80",
        "description": "Ultra-lightweight memory titanium frames with 9-layer TAC polarized lenses cutting glare over snow and water.",
        "features": ["Japanese beta-titanium flexible frame", "9-layer TAC polarized lenses", "Hydrophobic oil and water repelling coating", "Weighs only 16 grams"],
        "tags": ["sunglasses", "polarized", "titanium", "outdoor", "eyewear"],
        "elasticity": -1.50,
        "inStoreAisle": "Aisle 8C (Eyewear & Accessories)",
        "returnRiskScore": 10
    },
    {
        "id": "prod-089",
        "name": "Double Camping Hammock with Integrated Mosquito Bug Net (500 lb)",
        "category": "Outdoor",
        "price": 49.00,
        "originalPrice": 62.00,
        "rating": 4.86,
        "reviewsCount": 560,
        "stock": 50,
        "image": "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=80",
        "description": "210T parachute nylon hammock with micro-mesh bug netting and tree-friendly non-stretch suspension straps.",
        "features": ["210T high-tenacity parachute nylon", "2100 holes/sq inch micro-mesh net", "Includes two 10ft 16-loop tree straps", "500 lb weight capacity rating"],
        "tags": ["hammock", "camping", "bug net", "relax", "travel"],
        "elasticity": -1.70,
        "inStoreAisle": "Aisle 8A (Camp Furniture)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-090",
        "name": "Insulated Stainless Steel 64oz Vacuum Beer & Beverage Growler",
        "category": "Outdoor",
        "price": 52.00,
        "originalPrice": 65.00,
        "rating": 4.88,
        "reviewsCount": 290,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80",
        "description": "Heavy-duty swing-top growler holding carbonation and keeping drinks frosty cold for up to 48 hours.",
        "features": ["64 oz half-gallon volume", "Swing-top wire lock maintains carbonation", "18/8 food-grade stainless steel", "Keeps drinks cold 48h / hot 24h"],
        "tags": ["growler", "beer", "hydration", "camping", "insulated"],
        "elasticity": -1.40,
        "inStoreAisle": "Aisle 8B (Camp Kitchen)",
        "returnRiskScore": 4
    },

    # --- 10. Toys, Creative Hobbies & Crafts (prod-091 to prod-100) ---
    {
        "id": "prod-091",
        "name": "Architectural Solid Beechwood 100-Piece Modular Building Block Set",
        "category": "Toys & Hobbies",
        "price": 64.00,
        "originalPrice": 79.00,
        "rating": 4.92,
        "reviewsCount": 380,
        "stock": 40,
        "image": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80",
        "description": "Precision-cut natural European beech blocks inspiring open-ended spatial reasoning without plastic parts.",
        "features": ["100 precision geometric blocks", "Solid sustainably sourced beechwood", "Smooth hand-sanded splinter-free finish", "Wooden slide-lid storage crate included"],
        "tags": ["wooden toys", "building blocks", "montessori", "stem", "creative toys", "kids"],
        "elasticity": -1.50,
        "inStoreAisle": "Aisle 10A (Wooden Toys & STEM)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-092",
        "name": "Artist Extra-Fine Watercolor Pan Set (36 Vibrant Pigments)",
        "category": "Toys & Hobbies",
        "price": 48.00,
        "originalPrice": 60.00,
        "rating": 4.90,
        "reviewsCount": 470,
        "stock": 50,
        "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80",
        "description": "Lightfast artist pigments bound with gum arabic, housed in a durable travel enamel tin with fold-out mixing palette.",
        "features": ["36 saturated half-pan pigments", "High lightfastness ratings", "Enamel metal tin with foldout palette", "Includes two squirrel-hair round brushes"],
        "tags": ["watercolor", "art supplies", "painting", "crafts", "hobbies"],
        "elasticity": -1.65,
        "inStoreAisle": "Aisle 10C (Art & Fine Painting)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-093",
        "name": "Vintage Mechanical Brass Orrery Solar System Desk Model Kit",
        "category": "Toys & Hobbies",
        "price": 89.00,
        "originalPrice": 115.00,
        "rating": 4.88,
        "reviewsCount": 210,
        "stock": 25,
        "image": "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        "description": "Geared mechanical model demonstrating planetary orbital mechanics with winding clockwork mechanism.",
        "features": ["All-metal precision brass gear train", "Hand-cranked orbital motion", "Semi-precious stone planet spheres", "Engraved zodiac calendar base"],
        "tags": ["orrery", "solar system", "model kit", "mechanical", "astronomy"],
        "elasticity": -1.25,
        "inStoreAisle": "Aisle 10B (Mechanical Models)",
        "returnRiskScore": 8
    },
    {
        "id": "prod-094",
        "name": "Professional 32-Piece Graphite & Charcoal Drawing Art Set",
        "category": "Toys & Hobbies",
        "price": 32.00,
        "originalPrice": 42.00,
        "rating": 4.84,
        "reviewsCount": 610,
        "stock": 65,
        "image": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80",
        "description": "Graded graphite pencils (5H to 8B), willow charcoal sticks, blending stumps, and kneaded eraser in zippered case.",
        "features": ["Graded pencils from 5H hard to 8B soft", "Natural willow & compressed charcoal", "Paper blending tortillions & kneaded rubber", "Compact travel zippered organizer"],
        "tags": ["sketching", "drawing", "pencils", "charcoal", "art"],
        "elasticity": -1.80,
        "inStoreAisle": "Aisle 10C (Drawing & Sketching)",
        "returnRiskScore": 4
    },
    {
        "id": "prod-095",
        "name": "Botanical DIY Closed Terrarium Ecosystem Starter Kit",
        "category": "Toys & Hobbies",
        "price": 45.00,
        "originalPrice": 55.00,
        "rating": 4.81,
        "reviewsCount": 340,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=800&q=80",
        "description": "Geodesic glass vessel with activated charcoal, volcanic drainage gravel, sphagnum moss, and miniature brass tools.",
        "features": ["Handcrafted geometric glass jar with cork", "Activated carbon air purification layer", "Miniature long-reach planting tools", "Illustrated botanical care guide book"],
        "tags": ["terrarium", "diy kit", "plants", "gardening", "craft kit"],
        "elasticity": -1.55,
        "inStoreAisle": "Aisle 10D (Nature & Botany Kits)",
        "returnRiskScore": 7
    },
    {
        "id": "prod-096",
        "name": "Programmable STEM Robotics Buggy Kit (ESP32 Bluetooth / WiFi)",
        "category": "Toys & Hobbies",
        "price": 68.00,
        "originalPrice": 85.00,
        "rating": 4.87,
        "reviewsCount": 260,
        "stock": 30,
        "image": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80",
        "description": "Learn coding with block programming or Python, equipped with ultrasonic obstacle avoidance and line tracking sensors.",
        "features": ["ESP32 microcontroller with WiFi/BLE", "Ultrasonic sensor & line follower module", "Scratch & MicroPython tutorials included", "Rechargeable 18650 battery holder"],
        "tags": ["robotics", "stem", "coding", "esp32", "electronics kit", "kids education"],
        "elasticity": -1.35,
        "inStoreAisle": "Aisle 10A (STEM Electronics)",
        "returnRiskScore": 11
    },
    {
        "id": "prod-097",
        "name": "Optical K9 Crystal Triangular Prism & Desktop Kaleidoscope",
        "category": "Toys & Hobbies",
        "price": 24.00,
        "originalPrice": 30.00,
        "rating": 4.79,
        "reviewsCount": 390,
        "stock": 70,
        "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80",
        "description": "Polished optical glass casting brilliant spectral rainbows, paired with vintage brass kaleidoscope.",
        "features": ["Flawless K9 optical crystal glass", "Generates vivid full-spectrum rainbows", "Antique brass finish body barrel", "Felt-lined padded gift box"],
        "tags": ["prism", "optics", "physics", "kaleidoscope", "desk toy"],
        "elasticity": -1.90,
        "inStoreAisle": "Aisle 10B (Science & Optics)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-098",
        "name": "Handcrafted Acrylic Calligraphy Fountain Pen & Archival Ink Set",
        "category": "Toys & Hobbies",
        "price": 38.00,
        "originalPrice": 48.00,
        "rating": 4.86,
        "reviewsCount": 420,
        "stock": 45,
        "image": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=800&q=80",
        "description": "German iridium medium nib with piston converter and 50ml bottle of waterproof black archival drawing ink.",
        "features": ["German fine-point iridium nib", "Piston ink filling vacuum converter", "Turned acrylic resin marbled body", "Includes 50ml waterproof archival black ink"],
        "tags": ["fountain pen", "calligraphy", "writing", "stationery", "journaling"],
        "elasticity": -1.60,
        "inStoreAisle": "Aisle 10C (Writing & Calligraphy)",
        "returnRiskScore": 5
    },
    {
        "id": "prod-099",
        "name": "Terra Nova Tabletop Civilization Strategy Board Game",
        "category": "Toys & Hobbies",
        "price": 59.00,
        "originalPrice": 72.00,
        "rating": 4.94,
        "reviewsCount": 540,
        "stock": 28,
        "image": "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80",
        "description": "Engaging engine-building strategy game for 2-4 players with wooden resource meeples and modular hex map board.",
        "features": ["Plays 2-4 players (60-90 minutes)", "Over 200 custom screen-printed wooden meeples", "Double-sided modular terrain hex board", "Solo automa player mode included"],
        "tags": ["board game", "strategy game", "tabletop", "family games", "meeples"],
        "elasticity": -1.30,
        "inStoreAisle": "Aisle 10E (Board Games)",
        "returnRiskScore": 6
    },
    {
        "id": "prod-100",
        "name": "Vintage Dual-Lens Retro Instant Film Camera with Color Filters",
        "category": "Toys & Hobbies",
        "price": 99.00,
        "originalPrice": 125.00,
        "rating": 4.85,
        "reviewsCount": 630,
        "stock": 35,
        "image": "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80",
        "description": "Twin-lens reflex waist-level viewfinder instant camera with built-in flash, selfie mirror, and magnetic color filters.",
        "features": ["Waist-level optical viewfinder", "Built-in automatic exposure flash", "Uses standard instant credit-card size film", "Includes 4 magnetic creative tint lens filters"],
        "tags": ["instant camera", "film camera", "photography", "retro", "vintage", "camera"],
        "elasticity": -1.45,
        "inStoreAisle": "Aisle 10B (Retro Photography)",
        "returnRiskScore": 12
    }
]

print(f"Total products curated: {len(PRODUCTS)}")

# Write to src/data/mockCatalog.ts
ts_content = f"""import {{ Product }} from '../types';

export const MOCK_PRODUCTS: Product[] = {json.dumps(PRODUCTS, indent=2)};
"""

with open("src/data/mockCatalog.ts", "w") as f:
    f.write(ts_content)

print("Wrote 100 products to src/data/mockCatalog.ts")
